### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by viniarruda** [viniarruda/api-ecommerce#1]
Next steps

- [ ] Change Rails to NestJs
- [ ] Create database using postgres
- [ ] Create migrations

Create controllers
- [ ] Auth
- [ ] Products
  - GET ALL
  - GET ID
  - POST
  - PUT
  - DELETE
- [ ] Users
  - GET ALL
  - GET ID
  - POST
  - PUT
  - DELETE
- [ ] Highlights
  - WHERE PRODUCT.HIGHLIGHT = 1

**Comment by vinyvicente** [comment]
Products needs of attributes, or not? What do you think about the search engine or cache?

**Comment by viniarruda** [comment]
> Products needs of attributes, or not? What do you think about the search engine or cache?

Definitely yes. My first ideia is change the rails to nest, after is start structuring the database.

We can use only this attributes first:

```
t.integer :sku
t.string :item
t.string :description
t.string :color
t.string :size
t.integer :cod
t.integer :stock
t.boolean :highlight
```
With the basic attributes, the front back to run normally and I start change the Back and Front to the best ideas for shop template. What do you think? 

The front It's currently like this: https://www.figma.com/file/LphHTYVMReEKHY8OMTjxZucW/E-commerce?node-id=0%3A1
